# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3640fb39bcf605de0537d6dfc0d01c8a"
name = "CF Ready"
handle = "cf-ready"
application_url = "https://cf-ready-prod.tmsf.workers.dev"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_validations"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/update"
  topics = [ "shop/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/billing"
  topics = [ "app_subscriptions/update", "app_purchases_one_time/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[auth]
redirect_urls = [ "https://cf-ready-prod.tmsf.workers.dev/auth/callback" ]

[build]
automatically_update_urls_on_dev = false
